"use client";

import React, { useState } from "react";
import { jsPDF } from "jspdf";
import { Download, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { InvestmentReport } from "@/types";

interface PDFExporterProps {
  report: InvestmentReport;
}

export function PDFExporter({ report }: PDFExporterProps) {
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = async () => {
    setIsExporting(true);
    try {
      const doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      let yPos = 20;

      // Color Palette Constants
      const primaryColor = [16, 185, 129]; // emerald-500
      const textColor = [23, 23, 23]; // slate-900
      const mutedTextColor = [100, 116, 139]; // slate-500
      const lightBg = [248, 250, 252]; // slate-50

      // Helper to add clean section headers
      const addSectionHeader = (title: string) => {
        if (yPos > 260) {
          doc.addPage();
          yPos = 20;
        }
        doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
        doc.rect(15, yPos - 4, 180, 8, "F");
        
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        doc.text(title.toUpperCase(), 18, yPos + 1.5);
        yPos += 12;
      };

      // Header Banner
      doc.setFillColor(30, 41, 59); // slate-800
      doc.rect(0, 0, 210, 32, "F");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(18);
      doc.setTextColor(255, 255, 255);
      doc.text("INVESTMENT RESEARCH REPORT", 15, 18);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(148, 163, 184); // slate-400
      doc.text(`Generated by InvestIQ Terminal  |  Date: ${new Date(report.analyzedAt).toLocaleDateString()}`, 15, 24);

      yPos = 44;

      // Company Overview
      doc.setFont("helvetica", "bold");
      doc.setFontSize(15);
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
      doc.text(`${report.overview.name} (${report.overview.ticker})`, 15, yPos);
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(mutedTextColor[0], mutedTextColor[1], mutedTextColor[2]);
      doc.text(`${report.overview.sector}  •  ${report.overview.industry}`, 15, yPos + 5);

      // Score Callout Box
      doc.setDrawColor(226, 232, 240); // slate-200
      doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
      doc.rect(145, yPos - 6, 50, 18, "FD");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(mutedTextColor[0], mutedTextColor[1], mutedTextColor[2]);
      doc.text("RECOMMENDATION", 149, yPos - 1);

      doc.setFontSize(14);
      const ratingColor = 
        report.recommendation === "INVEST" ? [16, 185, 129] : 
        report.recommendation === "HOLD" ? [245, 158, 11] : [244, 63, 94];
      doc.setTextColor(ratingColor[0], ratingColor[1], ratingColor[2]);
      doc.text(report.recommendation, 149, yPos + 5);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
      doc.text(`Score: ${report.score}/100`, 149, yPos + 10);

      yPos += 18;

      // Summary Description
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
      const descLines = doc.splitTextToSize(report.overview.description, 180);
      doc.text(descLines, 15, yPos);
      yPos += descLines.length * 5 + 4;

      // Pricing details
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(mutedTextColor[0], mutedTextColor[1], mutedTextColor[2]);
      doc.text(`Share Price: $${report.overview.price}  •  Market Cap: ${report.overview.marketCap}  •  P/E Ratio: ${report.overview.peRatio}x`, 15, yPos);
      yPos += 14;

      // Financial Analysis
      addSectionHeader("Financial Health Indicators");
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
      doc.text(`• 3-Year Annualized Revenue Growth: ${report.financial_health.revenueGrowth3Y}%`, 18, yPos);
      doc.text(`• Corporate Operating Margins: ${report.financial_health.operatingMargin}%`, 18, yPos + 5);
      doc.text(`• Debt to Equity Leverage Ratio: ${report.financial_health.debtToEquity.toFixed(2)}`, 18, yPos + 10);
      doc.text(`• Annual Free Cash Flow Capacity: ${report.financial_health.freeCashFlow}`, 18, yPos + 15);
      
      yPos += 26;

      // Market Position
      addSectionHeader("Market Position & Industry Trends");
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
      doc.text(`• Addressable Market Size: ${report.market_position.marketSize}`, 18, yPos);
      doc.text(`• Calculated Market Share: ${report.market_position.marketShare}%`, 18, yPos + 5);
      doc.text(`• Competitors: ${report.market_position.competitors.join(", ")}`, 18, yPos + 10);
      
      yPos += 20;

      // Risks Section
      addSectionHeader("Risk Profile & Regulatory Factors");
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
      doc.text(`• Overall Risk Score: ${report.risks.riskScore}/100`, 18, yPos);
      
      doc.text("• Key Risk Factors:", 18, yPos + 5);
      let riskOffset = yPos + 10;
      report.risks.riskFactors.forEach(risk => {
        const lines = doc.splitTextToSize(`- ${risk}`, 170);
        doc.text(lines, 22, riskOffset);
        riskOffset += lines.length * 4.5;
      });

      yPos = riskOffset + 5;

      // Page Break for Thesis
      doc.addPage();
      yPos = 20;

      // Bull and Bear cases
      addSectionHeader("Investment Thesis (Bull vs. Bear Cases)");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(16, 185, 129); // Green
      doc.text("BULL CASE (Growth Drivers)", 18, yPos);
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
      let bullOffset = yPos + 5;
      report.bull_case.forEach(pt => {
        const lines = doc.splitTextToSize(`- ${pt}`, 174);
        doc.text(lines, 18, bullOffset);
        bullOffset += lines.length * 4.5;
      });

      yPos = bullOffset + 6;

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(244, 63, 94); // Red
      doc.text("BEAR CASE (Core Risks)", 18, yPos);
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
      let bearOffset = yPos + 5;
      report.bear_case.forEach(pt => {
        const lines = doc.splitTextToSize(`- ${pt}`, 174);
        doc.text(lines, 18, bearOffset);
        bearOffset += lines.length * 4.5;
      });

      yPos = bearOffset + 12;

      // Final Reasoning
      addSectionHeader("Final Committee Logic");
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
      const reasoningLines = doc.splitTextToSize(report.final_reasoning, 180);
      doc.text(reasoningLines, 15, yPos);

      // Save document
      doc.save(`${report.ticker.toUpperCase()}_Investment_Research.pdf`);
    } catch (err) {
      console.error("PDF Export error:", err);
      alert("Failed to export PDF. Please check console.");
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Button
      variant="outline"
      onClick={handleExport}
      disabled={isExporting}
      className="flex items-center gap-2"
    >
      {isExporting ? (
        <Loader2 className="w-4 h-4 animate-spin" />
      ) : (
        <Download className="w-4 h-4" />
      )}
      Export PDF Report
    </Button>
  );
}
